"""initial schema with indexes and cascades

Revision ID: 0f550a14e217
Revises: 
Create Date: 2026-05-14 21:45:02.603144
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f550a14e217'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bindings_parent_id'), 'bindings', ['parent_id'], unique=False)
    op.create_index(op.f('ix_bindings_student_id'), 'bindings', ['student_id'], unique=False)
    op.drop_constraint('bindings_student_id_fkey', 'bindings', type_='foreignkey')
    op.drop_constraint('bindings_parent_id_fkey', 'bindings', type_='foreignkey')
    op.create_foreign_key(None, 'bindings', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bindings', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_chat_summaries_binding_id'), 'chat_summaries', ['binding_id'], unique=False)
    op.create_index(op.f('ix_chat_summaries_student_id'), 'chat_summaries', ['student_id'], unique=False)
    op.drop_constraint('chat_summaries_binding_id_fkey', 'chat_summaries', type_='foreignkey')
    op.drop_constraint('chat_summaries_student_id_fkey', 'chat_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'chat_summaries', 'bindings', ['binding_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_summaries', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_context_materials_student_id'), 'context_materials', ['student_id'], unique=False)
    op.drop_constraint('context_materials_student_id_fkey', 'context_materials', type_='foreignkey')
    op.create_foreign_key(None, 'context_materials', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversations_binding_id'), 'conversations', ['binding_id'], unique=False)
    op.drop_constraint('conversations_binding_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'bindings', ['binding_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_notifications_student_unread', 'notifications', ['student_id', 'is_read'], unique=False)
    op.drop_constraint('notifications_student_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('persona_configs_student_id_fkey', 'persona_configs', type_='foreignkey')
    op.create_foreign_key(None, 'persona_configs', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('students', 'summary_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('students', 'summary_interval',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.drop_constraint('voice_profiles_student_id_fkey', 'voice_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'voice_profiles', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_profiles', type_='foreignkey')
    op.create_foreign_key('voice_profiles_student_id_fkey', 'voice_profiles', 'students', ['student_id'], ['id'])
    op.alter_column('students', 'summary_interval',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('students', 'summary_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'persona_configs', type_='foreignkey')
    op.create_foreign_key('persona_configs_student_id_fkey', 'persona_configs', 'students', ['student_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_student_id_fkey', 'notifications', 'students', ['student_id'], ['id'])
    op.drop_index('ix_notifications_student_unread', table_name='notifications')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_binding_id_fkey', 'conversations', 'bindings', ['binding_id'], ['id'])
    op.drop_index(op.f('ix_conversations_binding_id'), table_name='conversations')
    op.drop_constraint(None, 'context_materials', type_='foreignkey')
    op.create_foreign_key('context_materials_student_id_fkey', 'context_materials', 'students', ['student_id'], ['id'])
    op.drop_index(op.f('ix_context_materials_student_id'), table_name='context_materials')
    op.drop_constraint(None, 'chat_summaries', type_='foreignkey')
    op.drop_constraint(None, 'chat_summaries', type_='foreignkey')
    op.create_foreign_key('chat_summaries_student_id_fkey', 'chat_summaries', 'students', ['student_id'], ['id'])
    op.create_foreign_key('chat_summaries_binding_id_fkey', 'chat_summaries', 'bindings', ['binding_id'], ['id'])
    op.drop_index(op.f('ix_chat_summaries_student_id'), table_name='chat_summaries')
    op.drop_index(op.f('ix_chat_summaries_binding_id'), table_name='chat_summaries')
    op.drop_constraint(None, 'bindings', type_='foreignkey')
    op.drop_constraint(None, 'bindings', type_='foreignkey')
    op.create_foreign_key('bindings_parent_id_fkey', 'bindings', 'parents', ['parent_id'], ['id'])
    op.create_foreign_key('bindings_student_id_fkey', 'bindings', 'students', ['student_id'], ['id'])
    op.drop_index(op.f('ix_bindings_student_id'), table_name='bindings')
    op.drop_index(op.f('ix_bindings_parent_id'), table_name='bindings')
    # ### end Alembic commands ###
